export const dummyData = [
  {
    id: 1,
    type: 'outcome',
    date: '18/01/2023',
    title: 'Launch',
    category: 'Needs',
    source: 'Gopay',
    total: 100000,
  },
  {
    id: 2,
    type: 'income',
    date: '25/01/2023',
    title: 'Monthly Salary',
    category: 'Revenue',
    source: 'Bank BCA',
    total: 10000000,
  },
  {
    id: 3,
    type: 'outcome',
    date: '26/01/2023',
    title: 'Monthly Expenses',
    category: 'Monthly Expenses',
    source: 'Uang Tunai',
    total: 1000000,
  },
  {
    id: 4,
    type: 'outcome',
    date: '26/01/2023',
    title: 'Car Gasoline',
    category: 'Transportations',
    source: 'Gopay',
    total: 300000,
  },
  {
    id: 5,
    type: 'income',
    date: '26/01/2023',
    title: 'Freelance Salary',
    category: 'Monthly Expenses',
    source: 'Bank BCA',
    total: 1500000,
  },
  {
    id: 6,
    type: 'outcome',
    date: '26/01/2023',
    title: 'Car Gasoline',
    category: 'Transportations',
    source: 'Uang Tunai',
    total: 300000,
  },
  {
    id: 7,
    type: 'income',
    date: '26/01/2023',
    title: 'Freelance Salary',
    category: 'Monthly Expenses',
    source: 'Bank BCA',
    total: 1500000,
  },
  {
    id: 8,
    type: 'outcome',
    date: '26/01/2023',
    title: 'Car Gasoline',
    category: 'Transportations',
    source: 'Uang Tunai',
    total: 300000,
  },
  {
    id: 9,
    type: 'income',
    date: '26/01/2023',
    title: 'Freelance Salary',
    category: 'Monthly Expenses',
    source: 'Bank BCA',
    total: 1500000,
  },
  {
    id: 10,
    type: 'income',
    date: '26/01/2023',
    title: 'Freelance Salary',
    category: 'Monthly Expenses',
    source: 'Bank BCA',
    total: 1500000,
  },
];
